name: Develop CI

on:
  pull_request:
    branches:
      - develop
    
jobs:
  login-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Run login tests
      run: bash ./gradlew :login:testDebugUnitTest
