name: Develop CI

on:
  pull_request:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v2
  - uses: joschi/setup-jdk@v2
    with:
      java-version: '11' # The OpenJDK version to make available on the path
      architecture: 'x64' # defaults to 'x64'

    - name: Run tests
      run: sudo ./mvnw clean install -e -X
